# Generated by Django 5.2.3 on 2025-06-13 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datalogger", models.UUIDField()),
                ("at", models.DateTimeField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("temp", "Temperature"),
                            ("rain", "Rain"),
                            ("hum", "Humidity"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["datalogger", "at"],
                        name="metrics_met_datalog_af14f9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("datalogger", "at", "label"),
                        name="unique_metric_per_datalogger_time_label",
                    )
                ],
            },
        ),
    ]
